# Use the official Python image as a base
FROM python:3.9

# Set working directory in the container
WORKDIR /app

# Copy and install requirements
COPY ./requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire backend directory into the container
COPY . .

# Expose the port the app runs on
EXPOSE 8000

# Command to run the application
CMD ["uvicorn", "fast:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
